# Generated by Django 5.1.3 on 2024-11-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rawnorsemenshow",
            options={
                "verbose_name": "Raw Norsemen Show",
                "verbose_name_plural": "Raw Norsemen Show",
            },
        ),
        migrations.AlterModelOptions(
            name="rawvikingsnfl",
            options={
                "verbose_name": "Raw Vikings NFL",
                "verbose_name_plural": "Raw Vikings NFL",
            },
        ),
        migrations.AlterModelOptions(
            name="rawvikingsshow",
            options={
                "verbose_name": "Raw Vikings Show",
                "verbose_name_plural": "Raw Vikings Show",
            },
        ),
    ]
