# Generated by Django 5.1.3 on 2024-11-30 14:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0002_alter_rawnorsemenshow_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NorsemenShow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("character_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Norsemen Show",
                "verbose_name_plural": "Norsemen Show",
            },
        ),
    ]
