# Generated by Django 5.1.3 on 2024-11-30 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0004_vikingsshow"),
    ]

    operations = [
        migrations.CreateModel(
            name="VikingsNFL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("player_name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("height", models.CharField(max_length=255)),
                ("weight", models.CharField(max_length=255)),
                ("college", models.CharField(max_length=255)),
                ("experience", models.CharField(max_length=255)),
                ("profile_link", models.URLField(max_length=500)),
                ("biography_html", models.TextField(blank=True, null=True)),
                ("image_src", models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "Vikings NFL",
                "verbose_name_plural": "Vikings NFL",
            },
        ),
    ]
