# Generated by Django 5.1.3 on 2024-11-30 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl", "0005_vikingsnfl"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("games_played", models.IntegerField(blank=True, null=True)),
                ("games_started", models.IntegerField(blank=True, null=True)),
                ("touchdowns", models.IntegerField(blank=True, null=True)),
                ("attempts", models.IntegerField(blank=True, null=True)),
                (
                    "average",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("fumbles", models.IntegerField(blank=True, null=True)),
                ("longest", models.IntegerField(blank=True, null=True)),
                ("receptions", models.IntegerField(blank=True, null=True)),
                ("yards", models.IntegerField(blank=True, null=True)),
                ("lost", models.IntegerField(blank=True, null=True)),
                ("team", models.CharField(blank=True, max_length=255, null=True)),
                ("season", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_stats",
                        to="etl.vikingsnfl",
                    ),
                ),
            ],
            options={
                "verbose_name": "Career Stat",
                "verbose_name_plural": "Career Stats",
            },
        ),
    ]
